apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp-jdg-datalake-datagrid-pvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
      # directory location on host
      path: /opt/datagrid/standalone/partitioned_data
      # this field is optional
      type: Directory
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: ocp-jdg-datalake-datagrid-claim
    namespace: myproject
